name: opm
version: 1.0.0+1
publish_to: none
description: One Piece Manga Reader.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cached_network_image: ^3.2.2
  pinch_zoom_image_last: 0.4.1
  lottie: ^1.4.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/imgs/
  fonts: 
    - family: opfont
      fonts: 
        - asset: assets/fonts/one_piece_font.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/imgs/logo.png"
    background_color: "#222222"
    theme_color: "#222222"
  windows:
    generate: true
    image_path: "assets/imgs/logo.png"
    icon_size: 48 # min:48, max:256, default: 48